# config/meta.yml
meta_title: "Dinner just got a whole lot easier."
meta_description: "Dinja delivers everything you need to cook dinner after you pick out the recipes online. Say goodbye to the supermarket!"
meta_image: "facebook.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@amcdaid106" # indispensable pour les Twitter Cards
